---
title: "Overview of Scheduled Unit Tests of Jasp Modules"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{actions-dashboard}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include=FALSE}
library(actionsDashboard)
repos <- get_jasp_repos()
messages <- capture.output({
  tib_individual  <- try(get_action_data_as_tib(repos))
})
if (inherits(tib_individual, "try-error")) {
  print(messages)
  print(tib_individual)
  p_collapsed_runs <- repos_successful <- p_individual_runs <- NA
  print("Failed to get action data")
} else {
  print("Successfully retrieved action data")
  tib_collapsed     <- get_collapsed_tib(tib_individual)
  p_collapsed_runs  <- plot_collapsed_runs(tib_collapsed)
  repos_successful  <- repos[repos %in% tib_individual$repo]
  p_individual_runs <- plot_individual_runs(repos_successful, tib_individual)
}
```

## Aggregated runs per module
```{r overview _plot, fig.align='center', out.width="100%", echo=FALSE}
p_collapsed_runs
```

## Individual runs
Clicking on a dot opens the run log.
```{r individual_plot, fig.align='center', out.width="100%", echo=FALSE}
p_individual_runs
```

## Debug info
```{r}
Sys.time()
gh::gh_rate_limit()
print(messages)
print(repos_successful)
repos_failed <- setdiff(repos, repos_successful)
print(repos_failed)
```
